# Generated by Django 5.2.17 on 2026-10-03 11:07

import apps.restaurants.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Used in menu and QR code URLs.', max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='restaurants/covers/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.TextField(blank=True, help_text='e.g. Mon–Sat 08:00–22:00')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('default_language', models.CharField(choices=[('en', 'English'), ('tet', 'Tetum'), ('id', 'Bahasa Indonesia')], default='en', max_length=5)),
                ('default_prep_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(240)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive restaurants are hidden from the public.')),
                ('is_accepting_orders', models.BooleanField(default=True)),
                ('next_order_number', models.PositiveIntegerField(default=1001)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]{1,20}$', 'Use letters, numbers and dashes only (max 20), e.g. 12 or A-3.')])),
                ('label', models.CharField(blank=True, help_text="Optional, e.g. 'Terrace' or 'Window'.", max_length=60)),
                ('seats', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.restaurants.models._qr_token, editable=False, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='restaurants.table')),
            ],
            options={
                'verbose_name': 'QR code',
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurants.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('kitchen', 'Kitchen'), ('waiter', 'Waiter / Cashier')], default='waiter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'restaurant staff',
                'indexes': [models.Index(fields=['user', 'is_active'], name='restaurants_user_id_9f41f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'user'), name='unique_staff_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'number'), name='unique_table_number'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['table', 'is_active'], name='restaurants_table_i_af9cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['restaurant', 'status'], name='restaurants_restaur_a16ca5_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('table',), name='one_open_session_per_table'),
        ),
    ]
