# Generated by Django 5.2.17 on 2026-10-03 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cash_drawer_enabled',
            field=models.BooleanField(default=False, help_text='Open the cash drawer automatically when a cash payment is recorded.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='drawer_pin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pin 2 (most drawers)'), (1, 'Pin 5')], default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='printer_host',
            field=models.CharField(blank=True, help_text='IP address of the receipt printer the drawer is plugged into, e.g. 192.168.1.50', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='printer_port',
            field=models.PositiveIntegerField(default=9100, help_text='Raw printing port; 9100 for almost all network receipt printers.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
