# Generated by Django 5.2.17 on 2026-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_cash_drawer_enabled_restaurant_drawer_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='access_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
