# Generated by Django 5.2.17 on 2026-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_table_access_reset_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='access_reset_at',
        ),
        migrations.AddField(
            model_name='table',
            name='access_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
