# Generated by Django 5.2.17 on 2026-10-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_table_access_reset_at_table_access_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Thank you! Obrigadu! Terima kasih!', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='receipt_printer',
            field=models.CharField(choices=[('browser', "This device's printer (print dialog)"), ('network', 'Network receipt printer (prints directly)')], default='browser', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='receipt_prompt',
            field=models.CharField(choices=[('ask', 'Ask "Print receipt?" after each payment'), ('always', 'Always print after payment'), ('never', 'Never print automatically')], default='ask', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='receipt_width',
            field=models.PositiveSmallIntegerField(choices=[(48, '80 mm paper'), (32, '58 mm paper')], default=48, help_text='Paper width of the network receipt printer.'),
        ),
    ]
