# Generated by Django 5.2.17 on 2026-10-08 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_receipt_footer_restaurant_receipt_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='vat_enabled',
            field=models.BooleanField(default=False, help_text='Charge VAT on orders.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_inclusive',
            field=models.BooleanField(default=True, help_text='Ticked: menu prices already include VAT (totals stay the same, receipts show the VAT part). Unticked: VAT is added on top at checkout.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_label',
            field=models.CharField(default='VAT', help_text='Name printed on bills, e.g. VAT or IVA.', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Tax ID printed on receipts.', max_length=40),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
