# Generated by Django 5.2.17 on 2026-10-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_vat_enabled_restaurant_vat_inclusive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='vat_inclusive',
            field=models.BooleanField(default=False, help_text='Add on top: the bill total goes up by the VAT. Already included: totals stay the same and receipts show the VAT part.'),
        ),
    ]
