# Generated by Django 5.2.17 on 2026-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_vat_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cash_drawer_via_printer',
            field=models.BooleanField(default=False, help_text='The cash drawer is plugged into the receipt printer of this computer. A small slip prints to open it.'),
        ),
    ]
