# Generated by Django 5.2.17 on 2026-10-09 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_cash_drawer_via_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='branch_closed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the main branch deactivates this sub-branch.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The main branch this sub-branch belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_branches', to='restaurants.restaurant'),
        ),
    ]
