# Generated by Django 5.2.17 on 2026-10-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_branch_closed_at_restaurant_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='branch_flags',
            field=models.JSONField(blank=True, default=list, help_text='Reasons this request was flagged for review.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branch_owner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branch_registration_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branch_review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branch_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='storefront_photo',
            field=models.ImageField(blank=True, upload_to='restaurants/storefronts/'),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(help_text='e.g. your SERVE certificate number or tax number (NIF).', max_length=60, verbose_name='Business registration number')),
                ('owner_name', models.CharField(help_text='The legal owner of the business.', max_length=150, verbose_name='Owner name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='incomplete', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='restaurants.restaurant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
