# Generated by Django 5.2.17 on 2026-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_ref',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
