# Generated by Django 5.2.17 on 2026-10-08 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_placed_by_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_inclusive',
            field=models.BooleanField(default=False, help_text='VAT is part of the item prices (not added on top).'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
