# Generated by Django 5.2.17 on 2026-10-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('orders', '0004_order_vat_amount_order_vat_inclusive_order_vat_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='integrations.apikey'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('qr', 'QR code'), ('staff', 'Staff'), ('api', 'Ordering API')], default='qr', max_length=10),
        ),
    ]
