# Generated by Django 5.2.17 on 2026-10-04 01:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_restaurant_receipt_footer_restaurant_receipt_printer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('max_tables', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('max_menu_items', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('max_staff', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('is_active', models.BooleanField(default=True, help_text="Inactive plans can't be chosen for new subscriptions.")),
                ('is_public', models.BooleanField(default=True, help_text='Shown to restaurant owners on their Billing page.')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'price_monthly', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveSmallIntegerField(default=30, help_text='Free trial for new restaurants (0 = no trial).', validators=[django.core.validators.MaxValueValidator(365)])),
                ('grace_days', models.PositiveSmallIntegerField(default=7, help_text='Days after expiry before ordering is switched off.', validators=[django.core.validators.MaxValueValidator(60)])),
                ('invoice_days_before', models.PositiveSmallIntegerField(default=7, help_text='Create the next invoice this many days before the period ends.', validators=[django.core.validators.MaxValueValidator(60)])),
                ('payment_instructions', models.TextField(blank=True, help_text='Shown to restaurant owners on their Billing page and invoices (bank account, mobile money…).')),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('default_plan', models.ForeignKey(blank=True, help_text='Plan given to newly registered restaurants.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan')),
            ],
            options={
                'verbose_name': 'billing settings',
                'verbose_name_plural': 'billing settings',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('comped', models.BooleanField(default=False, help_text='Complimentary: never expires and is never invoiced.')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('requested_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='restaurants.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('plan_name', models.CharField(max_length=60)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('void', 'Void')], default='open', max_length=10)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='restaurants.restaurant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'), models.Index(fields=['restaurant', 'status'], name='billing_inv_restaur_8745f4_idx')],
            },
        ),
    ]
