# Generated by Django 5.2.17 on 2026-10-08 06:57

from django.db import migrations, models


def pro_gets_features(apps, schema_editor):
    """Analytics, cash register and quotations are Pro features."""
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(name__iexact="pro").update(
        feature_analytics=True, feature_cash_register=True, feature_quotations=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feature_analytics',
            field=models.BooleanField(default=False, help_text='Analytics page (trends, busy times, best sellers).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='feature_cash_register',
            field=models.BooleanField(default=False, help_text='Cash register: opening change and end-of-day reconciliation.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='feature_quotations',
            field=models.BooleanField(default=False, help_text='Quotations for catering and procurement bids.'),
        ),
        migrations.RunPython(pro_gets_features, migrations.RunPython.noop),
    ]
