# Generated by Django 5.2.17 on 2026-10-09 05:21

from django.db import migrations, models


def pro_gets_expenses(apps, schema_editor):
    """Expenses & profit is a Pro feature."""
    apps.get_model("billing", "Plan").objects.filter(name__iexact="pro").update(feature_expenses=True)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feature_expenses',
            field=models.BooleanField(default=False, help_text='Daily expenses and profit per day, week, month and year.'),
        ),
        migrations.RunPython(pro_gets_expenses, migrations.RunPython.noop),
    ]
