# Generated by Django 5.2.17 on 2026-10-09 05:59

from django.db import migrations, models


def pro_gets_branches(apps, schema_editor):
    """Branches is a Pro feature."""
    apps.get_model("billing", "Plan").objects.filter(name__iexact="pro").update(feature_branches=True)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_feature_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feature_branches',
            field=models.BooleanField(default=False, help_text='Several branches under one owner, with an all-branches overview.'),
        ),
        migrations.RunPython(pro_gets_branches, migrations.RunPython.noop),
    ]
