# Generated by Django 5.2.17 on 2026-10-09 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_feature_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='branch_flag_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='Flag an account for review when it requests more branches than this within 30 days.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch_slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extra branch slots this invoice buys (an add-on invoice); added when it is paid.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_branch_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly price of each extra branch above the included ones.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_branches',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sub-branches included in the price (0 = main branch only).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_branches',
            field=models.PositiveSmallIntegerField(default=0, help_text='Paid extra branch slots (add-ons).'),
        ),
    ]
