# Generated by Django 5.2.17 on 2026-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_branch_slots_for_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feature_api',
            field=models.BooleanField(default=False, help_text='Ordering API for websites, apps and delivery partners.'),
        ),
    ]
