# Generated by Django 5.2.17 on 2026-10-09 05:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0008_cash_drawer_via_printer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('ingredients', 'Ingredients & food supplies'), ('drinks', 'Drinks'), ('gas', 'Gas & fuel'), ('utilities', 'Electricity, water & internet'), ('rent', 'Rent'), ('salaries', 'Salaries & wages'), ('transport', 'Transport'), ('equipment', 'Equipment & tableware'), ('maintenance', 'Repairs & cleaning'), ('other', 'Other')], default='ingredients', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('paid_with', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='expenses_ex_restaur_941a20_idx')],
            },
        ),
    ]
