# Generated by Django 5.2.17 on 2026-10-09 06:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('restaurants', '0009_restaurant_branch_closed_at_restaurant_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('other', 'Other')], default='cash', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='expenses_re_restaur_81d105_idx')],
            },
        ),
    ]
