# Generated by Django 5.2.17 on 2026-10-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_revenueentry'),
        ('integrations', '0001_initial'),
        ('orders', '0005_order_api_key_order_external_ref_alter_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.apikey'),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='api_key_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entry', to='orders.order'),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=10),
        ),
    ]
